version: '3'

services:

  elasticsearch:
    build: ./elasticsearch
    ports:
      - '9200:9200'
    ulimits:
      memlock:
        soft: -1
        hard: -1

  logstash:
    depends_on:
      - elasticsearch
    build: ./logstash
    ports: 
      - '5001:5001'
    volumes:
      - '$PWD/logstash/ls_pipelines:/app/ls_pipelines'

  filebeat:
    depends_on:
      - logstash
    build: ./filebeat
    volumes:
      - '$PWD/filebeat/logs:/app/logs'

  # metricbeat:
  #   depends_on:
  #     - logstash
  #   build: ./metricbeat