version: '3'

services:
  logstash:
    build: ./logstash
    ports: 
      - '5001:5001'
    volumes:
      - '$PWD/logstash/ls_pipelines:/app/ls_pipelines'

  filebeat:
    build: ./filebeat
    volumes:
      - '$PWD/filebeat/logs:/app/logs'